In [7]:
#bildstein_station1_xyz_intensity_rgb_probs
import numpy as np
np.set_printoptions(precision=10, suppress=True)

In [8]:
load = np.load('bildstein_station1_xyz_intensity_rgb_probs.npy')

In [9]:
print(load.shape)

(29697591, 8)


In [19]:
#print(load[:100, :])
print(len(np.unique(np.amax(load, axis=1))))

2526


In [30]:
def point_entropy(probabilities):
    pnt_entropy = []
    for pnt_prob in probabilities:
        print(pnt_prob)
        print('###')
        print(np.log(pnt_prob))
        print()
        pnt_prob[pnt_prob == 0] = 1e-7
        entropy = -1*sum(pnt_prob*np.log(pnt_prob))
        pnt_entropy.append(entropy)
    return np.asarray(pnt_entropy)

In [31]:
entps = point_entropy(load[:5, :])

[0.0000576  0.0001564  0.0003178  0.001113   0.1932     0.8047
 0.0004632  0.00002354]
###
[ -9.766   -8.766   -8.055   -6.8     -1.644   -0.2173  -7.676  -10.66  ]

[0.0002906  0.0006285  0.00018    0.00021    0.7075     0.2898
 0.001057   0.00000983]
###
[ -8.14   -7.37   -8.625  -8.47   -0.346  -1.238  -6.85  -11.53 ]

[0.000707   0.002066   0.0003543  0.0004573  0.8276     0.1666
 0.001949   0.00001734]
###
[ -7.254   -6.184   -7.945   -7.69    -0.1892  -1.792   -6.242  -10.96  ]

[0.000707   0.002066   0.0003543  0.0004573  0.8276     0.1666
 0.001949   0.00001734]
###
[ -7.254   -6.184   -7.945   -7.69    -0.1892  -1.792   -6.242  -10.96  ]

[0.000707   0.002066   0.0003543  0.0004573  0.8276     0.1666
 0.001949   0.00001734]
###
[ -7.254   -6.184   -7.945   -7.69    -0.1892  -1.792   -6.242  -10.96  ]



In [32]:
print(entps)

[0.5082993507 0.6213187575 0.4917939901 0.4917939901 0.4917939901]


In [26]:

print(load[0])

[0.0000576  0.0001564  0.0003178  0.001113   0.1932     0.8047
 0.0004632  0.00002354]


In [33]:
print(entps/np.log(2))

[0.7333209526 0.8963734903 0.7095087507 0.7095087507 0.7095087507]


[0.8047 0.7075 0.8276 0.8276 0.8276]
