In [1]:
import glob
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import pickle
import matplotlib.pyplot as plt

In [ ]:
file_names = ['bildstein_station1_xyz_intensity_rgb.npy', 'sg27_station2_intensity_rgb.npy']
entropies_k = {}
entropies_val = {}
for k in tqdm(range(1, 21)):
    file_entropies = []
    val_entropies = []
    for idx, file in enumerate(file_names):
        read_file_name = os.path.join(os.path.join('./entropies/',str(k)), file)
        y = np.load(read_file_name)
        entropies = y[0]
        classes_pred = y[1]
        val_entropies.append(entropies[:50])
        mean_entropy = np.mean(entropies)
        file_entropies.append(mean_entropy)
    entropies_val[k] = val_entropies
    entropies_k[k] = np.mean(file_entropies)

In [ ]:
print(entropies_k)

In [ ]:
plt.figure(figsize=(8, 8))
key, value = [], []
for key_, value_ in entropies_k.items():
    if key_%2 == 0 or key_ == 1:
        key.append(key_)
        value.append(value_)
plt.plot(key, value)
plt.scatter(key, value, c='b')
plt.xticks(key)
plt.grid()
plt.show()

In [ ]:
for key, value in entropies_val.items():
    flat_list = [item for sublist in value for item in sublist]
    print(len(flat_list))

In [ ]:
label_pd = pd.read_csv('./sem8_labels_training/bildstein_station1_xyz_intensity_rgb.labels', header=None, delim_whitespace=True, dtype=np.uint8)

In [ ]:
labels = label_pd.values

In [ ]:
unique, counts = np.unique(labels, return_counts=True)
y = dict(zip(unique, counts))

In [ ]:
print(y)

In [ ]:
label_pd = pd.read_csv('./sem8_labels_training/sg27_station2_intensity_rgb.labels', header=None, delim_whitespace=True, dtype=np.uint8)

In [ ]:
labels = label_pd.values

In [ ]:
unique, counts = np.unique(labels, return_counts=True)
y = dict(zip(unique, counts))

In [ ]:
print(y)

In [ ]:
files = sorted(os.listdir('./corrupt_probs/'))
print(files)

In [ ]:
for file in files:
    probs = np.load('./corrupt_probs/'+file)
    print(probs.shape)

In [ ]:
file_1 = pd.read_csv('./bildstein_station1_xyz_intensity_rgb.labels')
file_2 = pd.read_csv('./sg27_station2_intensity_rgb.labels')
file_3 = pd.read_csv('./bildstein_station1_xyz_intensity_rgb_orig.labels')

In [ ]:
print(file_1.shape)
print(file_2.shape)
print(file_3.shape)

In [ ]:
import pickle
import open3d as o3d

In [ ]:
pcd = o3d.io.read_point_cloud('./bildstein_station1_xyz_intensity_rgb.ply')
print(np.asarray(pcd.points).shape)

In [ ]:
with open('./bildstein_station1_xyz_intensity_rgb_KDTree.pkl', 'rb') as f:
    search_tree = pickle.load(f)

In [ ]:
print(np.asarray(search_tree.data).shape)

In [ ]:
with open('./bildstein_station1_xyz_intensity_rgb_proj.pkl', 'rb') as f:
    proj = pickle.load(f)

In [ ]:
print(proj[1])

In [ ]:
with open('./snap-39501.meta', 'rb') as f:
    y = f.read()

In [ ]:
print(type(y))

In [ ]:
print(y[0])

In [ ]:
with open('./1/weights.pkl', 'rb') as f:
    data = pickle.load(f)

In [ ]:
for k, v in data.items():
    print(k, v.shape)

In [2]:
y = np.load('./bildstein_station1_xyz_intensity_rgb_probs.npy')

In [3]:
print(y.shape)
print(y[0])
probs = y[:10000, :]
print(np.isnan(probs).any())

(29697591, 8)
[-2.197  -2.006  -1.234  -0.921   0.7354  1.935  -1.593  -2.225 ]
False


In [4]:
import torch

In [5]:
m = torch.nn.Softmax(dim=1)
h = torch.from_numpy(probs)
h = h.type(torch.DoubleTensor)

In [6]:
print(h.shape)
print(h[0])

torch.Size([10000, 8])
tensor([-2.1973, -2.0059, -1.2344, -0.9209,  0.7354,  1.9346, -1.5928, -2.2246],
       dtype=torch.float64)


In [7]:
j = m(h)

In [15]:
print(j[1000], sum(j[100]))

tensor([0.0199, 0.0211, 0.0250, 0.0353, 0.2037, 0.6507, 0.0306, 0.0136],
       dtype=torch.float64) tensor(1., dtype=torch.float64)


In [16]:
np_ = j.numpy()

In [17]:
print(np_)

[[0.01083587 0.01312172 0.02838194 ... 0.67499027 0.01983314 0.0105436 ]
 [0.01620169 0.01701242 0.01920244 ... 0.68422019 0.02885445 0.01206361]
 [0.01535167 0.01591652 0.01807104 ... 0.68409688 0.02683799 0.01067541]
 ...
 [0.01983521 0.02146793 0.02802681 ... 0.64983358 0.02920025 0.01435669]
 [0.01983521 0.02146793 0.02802681 ... 0.64983358 0.02920025 0.01435669]
 [0.01983521 0.02146793 0.02802681 ... 0.64983358 0.02920025 0.01435669]]
