In [1]:
import numpy as np
import pandas as pd
import open3d as o3d
import matplotlib.pyplot as plt
from tqdm import tqdm

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
def read_and_preprocess(filepath, factor=1):
    pc = pd.read_csv(filepath, sep=' ',header=None,  dtype=np.float32).to_numpy()
    #pcd = o3d.io.read_point_cloud(filepath)
    #pc_xyz = np.asarray(pcd.points)
    #pc_rgb = np.asarray(pcd.colors)
    #print('ashfvas',len(pc_xyz))
    pc_xyz = pc[:, 0:3]
    pc_rgb = pc[:, 3:6]
    #randints = np.random.randint(0, high = pc_xyz.shape[0], size = int(factor*pc_xyz.shape[0]))
    randints = np.random.choice(range(0, 700000), size = 700000, replace=False)
    print('jfghjkdfbg', len(pc_xyz))
    pc_xyz = pc_xyz[randints, :]
    pc_rgb = pc_rgb[randints, :]
    return pc_xyz, pc_rgb, randints

def read_probs(filepath, randints):
    probs, labels = np.load(filepath)
    print('ashvas',len(labels))
    probs_downsampled = probs[randints]
    labels_downsampled = labels[randints]
    return probs_downsampled, labels_downsampled
    return probs, labels

In [3]:
def labels_to_colors(pc_labels):
    cmap = {0: [0, 0, 0],
            1: [0, 0, 1],
            2: [0, 1, 0],
            3: [1, 0, 0],
            4: [0, 1, 1],
            5: [1, 0, 1],
            6: [1, 1, 0],
            7: [0, 0.5, 0.5],
            8: [0.5, 0, 0.5]}
    print(pc_labels.shape)
    pc_clrs = np.asarray([cmap[x] for x in pc_labels])
    return pc_clrs

def convert_prob_colors(pc_probs):
    cmap = plt.get_cmap('viridis')
    pc_clrs = cmap(pc_probs)
    return pc_clrs

In [15]:
rgb_val = False
prob_val = True
# fn='conferenceRoom_1'
# fn='office_42'
# fn='office_3'
fn='pantry_1'
path = '/home/lokesh/Master_Thesis/Dataset_Study/S3DIS/dataset/Stanford3dDataset_v1.2_Aligned_Version/Area_5/'+fn+'/'+fn+'.txt'
fname = 'Area_5_'+fn+'_probs.npy'
x = ['./s3dis/10/', './max_probs_flipout/s3dis/10/', './entropy_val/entropies/s3dis/10/', './entropies_flipout/s3dis/10/']
# max_prob_path = './s3dis/10/'+fname
# max_prob_path = './max_probs_flipout/s3dis/10/'+fname
# max_prob_path = './entropy_val/entropies/s3dis/10/'+fname
# max_prob_path = './entropies_flipout/s3dis/10/'+fname
for x_ in x:
    max_prob_path = x_+fname
    pc_xyz, pc_rgb, dindices = read_and_preprocess(path, factor=1)
    pc_probs, pc_labels_detect = read_probs(max_prob_path, dindices)
    pc_labels_detect += 1
    print(np.unique(pc_labels_detect, return_counts=True))
    print(pc_labels_detect.shape)
    if rgb_val:
        print('RGB values')
        pc_clrs = pc_rgb
    elif prob_val:
        print('Probability values')
        pc_clrs = convert_prob_colors(pc_probs)[:, :3]
        pc_clrs_detect = labels_to_colors(pc_labels_detect)
    min_val, max_val = np.min(pc_clrs), np.max(pc_clrs)
    pc_clrs = (pc_clrs-min_val)/(max_val-min_val)
    print(np.min(pc_clrs), np.max(pc_clrs))
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(pc_xyz)
    pcd.colors = o3d.utility.Vector3dVector(pc_clrs)
    o3d.visualization.draw_geometries([pcd])

jfghjkdfbg 721359
ashvas 719348
(array([1., 2., 5., 6.]), array([ 20249, 120760, 437271, 121720]))
(700000,)
Probability values
(700000,)
0.0 1.0
jfghjkdfbg 721359
ashvas 719348
(array([1., 2., 4., 5., 6.]), array([ 16761, 114888,   6132, 202013, 360206]))
(700000,)
Probability values
(700000,)
0.0 1.0
jfghjkdfbg 721359
ashvas 719348
(array([1., 2., 5., 6.]), array([ 20249, 120760, 437271, 121720]))
(700000,)
Probability values
(700000,)
0.0 1.0
jfghjkdfbg 721359
ashvas 719348
(array([1., 2., 4., 5., 6.]), array([ 16761, 114888,   6132, 202013, 360206]))
(700000,)
Probability values
(700000,)
0.0 1.0


In [12]:
#pc_clrs = pc_clrs_detect


0.0 1.0
